# List of VHDL libraries.
LIBS      ?= work    neorv32
# List of paths to the corresponding libraries stated above.
LIB_PATHS ?= ../vhdl ../lib/neorv32/rtl/core
# Files to ignore in the above library paths.
IGNORED_FILES += ../lib/neorv32/rtl/core/mem/neorv32_imem.legacy.vhd
IGNORED_FILES += ../lib/neorv32/rtl/core/mem/neorv32_dmem.legacy.vhd
IGNORED_FILES += ../vhdl/vga/tb/vga_tb.vhdl

export LIBS
export LIB_PATHS
export IGNORED_FILES
