name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nikleberg/neorv32_soc:latest
      options: --mac-address=00:ab:ab:ab:ab:ab # for QuestaSim license

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build Software (for Sim)
      run: |
        cd sw
        make CLI_FLAGS+='-DSIMULATION=1' exe install

    - name: Run Simulation
      run: |
        cd sim
        vsim -c -do ../scripts/sim_compile.tcl
        vsim -c -do ../scripts/sim_test.tcl

    - name: Build Software (for Syn)
      run: |
        cd sw
        make clean exe install

    - name: Run Synthesis
      run: |
        cd quartus
        quartus_sh -t ../scripts/quartus_project.tcl
        quartus_sh -t ../scripts/quartus_compile.tcl

    - name: Archive CI Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ci_artifacts
        path: |
          sw/main.elf
          sw/neorv32_exe.bin
          quartus/output_files/*.sof
