name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nikleberg/dev-base
    strategy:
      fail-fast: false
      matrix:
        simulator:
          - questa
          - ghdl
          - nvc

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build Software
        run: |
          cd sw
          make CLI_FLAGS+='-DSIMULATION=1' exe install
      - name: Run Simulation
        run: |
          cd build
          make ${{matrix.simulator}} work.top
          make ${{matrix.simulator}} test

  synthesize:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nikleberg/dev-base
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build Software
        run: |
          cd sw
          make exe install
      - name: Run Synthesis
        run: |
          cd build
          make quartus work.top synth
      - name: Archive CI Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ci_artifacts
          path: |
            sw/main.elf
            sw/neorv32_exe.bin
            build/output_files/*.sof
